# Generated by Django 2.2 on 2019-05-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='app.Hashtag'),
        ),
    ]
